"""Free, deterministic answers for the portfolio demo when no API key is configured."""

import pandas as pd

from src.analysis import compute_kpis, customer_summary, product_trends, revenue_over_time, top_n_by
from src.insights import generate_insights


class LocalDataAssistant:
    """Answer supported business questions with auditable Pandas calculations."""

    mode = "built-in"

    def __init__(self, schema: dict, meta: dict):
        self.schema = schema
        self.meta = meta

    @staticmethod
    def _turn(question, answer, result=None, code="", chart=None, calculation="",
              interpretation="", recommendation="", next_question=""):
        return {
            "question": question, "method": "pandas", "code": code, "result": result,
            "chart": chart or {"type": "none"}, "answer": answer,
            "calculation": calculation, "interpretation": interpretation,
            "recommendation": recommendation, "next_question": next_question, "error": None,
        }

    def ask(self, question, df, engine=None, context=None, history=None, preferred="auto"):
        q = question.lower().strip()
        s = self.schema
        rev = s.get("revenue")
        product = s.get("product") or s.get("product_code")

        if product and rev and "product" in q and any(w in q for w in ["top", "best", "revenue"]):
            result = top_n_by(df, product, rev, 10).rename(columns={product: "Product", rev: "Revenue"})
            leader = result.iloc[0]
            return self._turn(question,
                f"{leader['Product']} is the top product, generating £{leader['Revenue']:,.2f} in revenue.",
                result, f'result = df.groupby("{product}")["{rev}"].sum().nlargest(10).reset_index()',
                {"type": "hbar", "x": "Product", "y": "Revenue", "title": "Top 10 products by revenue"},
                "Revenue was summed by product and ranked from highest to lowest.",
                "The leading products contribute disproportionately to sales.",
                "Protect availability of the strongest products and investigate cross-sell opportunities.",
                "Which products have declining sales?")

        if s.get("country") and rev and "country" in q:
            result = top_n_by(df, s["country"], rev, 10).rename(columns={s["country"]: "Country", rev: "Revenue"})
            leader = result.iloc[0]
            share = leader["Revenue"] / df[rev].sum()
            return self._turn(question,
                f"{leader['Country']} generates the most revenue: £{leader['Revenue']:,.2f}, or {share:.1%} of the total.",
                result, f'result = df.groupby("{s["country"]}")["{rev}"].sum().nlargest(10).reset_index()',
                {"type": "hbar", "x": "Country", "y": "Revenue", "title": "Top countries by revenue"},
                "Revenue was summed by country and ranked from highest to lowest.",
                "Revenue is concentrated in the leading market.",
                "Develop the next strongest markets to reduce geographic concentration risk.",
                "What is the average order value?")

        if s.get("date") and rev and any(w in q for w in ["month", "monthly"]):
            result = revenue_over_time(df, s)
            best = result.loc[result["Revenue"].idxmax()]
            return self._turn(question,
                f"{best['Period']:%B %Y} was the best sales month with £{best['Revenue']:,.2f} in revenue.",
                result, "result = revenue_over_time(df, schema)",
                {"type": "line", "x": "Period", "y": "Revenue", "title": "Monthly revenue"},
                "Revenue was grouped by calendar month and the highest month was selected.",
                "Peak months can indicate seasonal demand.",
                "Plan inventory and campaigns ahead of historically strong months.",
                "Which country generates the most revenue?")

        if any(phrase in q for phrase in ["average order", "order value", "aov"]):
            value = compute_kpis(df, s).get("Average Order Value")
            result = pd.DataFrame({"Metric": ["Average Order Value"], "Value": [value]})
            return self._turn(question, f"The average order value is £{value:,.2f}.", result,
                f'result = df.groupby("{s.get("invoice")}")["{rev}"].sum().mean()',
                calculation="Revenue was totaled per unique order, then averaged across all orders.",
                interpretation="This is the typical revenue generated by one completed order.",
                recommendation="Use bundles and relevant add-ons to lift order value.",
                next_question="Which country generates the most revenue?")

        if product and rev and any(w in q for w in ["declining", "decline", "falling"]):
            result = product_trends(df, s).dropna(subset=["Change %"])
            result = result[result["Change %"] < -20].sort_values("Change %").head(10)
            answer = (f"{len(result)} products in the displayed results declined by more than 20%."
                      if len(result) else "No qualifying products declined by more than 20%.")
            return self._turn(question, answer, result, "result = product_trends(df, schema)",
                {"type": "hbar", "x": "Product", "y": "Change %", "title": "Products with declining sales"},
                "Product revenue in the first and second halves of the period was compared.",
                "Large declines can indicate changing demand or availability problems.",
                "Review stock, pricing and promotions for the largest declines.",
                "What are my top 10 products?")

        if s.get("customer") and s.get("invoice") and any(w in q for w in ["customer", "frequently", "frequent"]):
            result = (customer_summary(df, s)
                      .rename(columns={s["customer"]: "Customer"})
                      .sort_values(["Orders", "Revenue"], ascending=False).head(10).reset_index(drop=True))
            leader = result.iloc[0]
            return self._turn(question,
                f"Customer {leader['Customer']} purchases most frequently with {int(leader['Orders'])} orders.",
                result, "result = customer_summary(df, schema).sort_values('Orders', ascending=False).head(10)",
                {"type": "hbar", "x": "Customer", "y": "Orders", "title": "Most frequent customers"},
                "Unique orders were counted for each customer and ranked.",
                "Frequent buyers are strong candidates for retention activity.",
                "Create a loyalty or personal outreach programme for repeat buyers.",
                "What is the average order value?")

        if any(w in q for w in ["cancelled", "canceled", "cancellation", "returned"]):
            rate = self.meta.get("cancel_rate")
            cancelled = self.meta.get("cancelled_orders", 0)
            orders = self.meta.get("orders_before", 0)
            if rate is not None:
                result = pd.DataFrame({"Orders": [orders], "Cancelled Orders": [cancelled], "Cancellation Rate": [rate]})
                return self._turn(question,
                    f"{cancelled:,} of {orders:,} orders were cancelled or returned, a rate of {rate:.1%}.",
                    result, "result = cancelled_orders / all_orders", calculation="Cancelled orders were divided by all orders before cleaning.",
                    interpretation="Cancellations create lost revenue and handling costs.",
                    recommendation="Break cancellations down by product and customer to find the main causes.",
                    next_question="Which products have declining sales?")

        if any(w in q for w in ["insight", "summary", "important"]):
            items = generate_insights(df, s, self.meta)[:3]
            result = pd.DataFrame([{"Finding": i["title"], "Calculated fact": i["fact"]} for i in items])
            answer = "The three most important calculated findings are shown below."
            return self._turn(question, answer, result, "result = generate_insights(df, schema, metadata)[:3]",
                calculation="Rule-based checks selected the strongest calculated findings.",
                interpretation="Together, these findings highlight performance, concentration and operational risk.",
                recommendation="Open Business Insights for the supporting detail behind every finding.",
                next_question="Which country generates the most revenue?")

        return self._turn(question,
            "Free demo mode currently supports the suggested questions shown above. Choose one of them, or add an OpenAI API key later for unrestricted questions.",
            calculation="No calculation was run because this question is outside the free demo question set.")
